INSTRUMENTS = [
    {
        "id": "guzheng",
        "image": "/static/photos/guzheng.jpg",
        "name": "古筝",
        "pinyin": "Guzheng",
        "category": "弹拨",
        "tone": "清越、流动、带有水波般的滑音",
        "era": "战国至秦汉形成，唐宋成熟",
        "summary": "古筝以二十一弦为常见形制，兼具宽广音域与细腻吟揉，是中国弹拨乐器中最具代表性的声音之一。",
        "story": "从宫廷雅乐到民间筝派，古筝不断吸收地域审美：河南筝豪放、山东筝铿锵、浙江筝清丽、潮州筝古雅。",
        "parts": ["面板", "筝码", "筝弦", "岳山", "筝首", "筝尾", "共鸣箱"],
        "techniques": ["托劈", "摇指", "滑音", "按揉", "刮奏"],
        "heritage": ["浙江筝派", "河南筝派", "潮州筝派", "客家筝派"],
        "gradient": "linear-gradient(135deg, #f7d797, #b86f2d)",
    },
    {
        "id": "pipa",
        "image": "/static/photos/pipa.jpg",
        "name": "琵琶",
        "pinyin": "Pipa",
        "category": "弹拨",
        "tone": "颗粒分明、刚柔并济，能文能武",
        "era": "汉魏传入，隋唐鼎盛",
        "summary": "琵琶四弦梨形，右手轮指如珠落玉盘，左手推拉吟揉，既能描摹十面埋伏的金戈铁马，也能诉说春江花月夜的温婉。",
        "story": "敦煌壁画中飞天怀抱琵琶，记录了丝路音乐交流。现代琵琶以十二平均律品相扩展转调能力。",
        "parts": ["琴头", "弦轴", "山口", "品相", "面板", "覆手", "琴弦"],
        "techniques": ["轮指", "扫弦", "挑", "泛音", "绞弦"],
        "heritage": ["浦东派", "平湖派", "崇明派", "无锡派"],
        "gradient": "linear-gradient(135deg, #d4a373, #6f3d2e)",
    },
    {
        "id": "erhu",
        "image": "/static/photos/erhu.jpg",
        "name": "二胡",
        "pinyin": "Erhu",
        "category": "拉弦",
        "tone": "近似人声，哀而不伤，极富歌唱性",
        "era": "唐宋胡琴演化，近现代独奏化",
        "summary": "二胡两弦一弓，结构简洁却表现力极强。琴皮与琴筒形成独特共鸣，让旋律拥有接近人声的情感曲线。",
        "story": "刘天华推动二胡进入现代音乐教育体系，《二泉映月》则让二胡成为中国音乐情感表达的象征。",
        "parts": ["琴杆", "琴筒", "琴皮", "琴轴", "千斤", "琴弦", "琴弓"],
        "techniques": ["揉弦", "滑音", "顿弓", "颤弓", "泛音"],
        "heritage": ["江南丝竹", "广东音乐", "北方说唱音乐"],
        "gradient": "linear-gradient(135deg, #c46b4f, #3d1f1b)",
    },
    {
        "id": "yangqin",
        "image": "/static/photos/yangqin.jpg",
        "name": "扬琴",
        "pinyin": "Yangqin",
        "category": "击弦",
        "tone": "明亮、晶莹，和声织体丰富",
        "era": "明清传入并中国化",
        "summary": "扬琴以琴竹击弦发声，能够演奏快速音型、分解和弦与华彩乐段，是民族乐队中的色彩与和声核心。",
        "story": "扬琴经由海上丝路传入后逐渐本土化，在广东音乐、江南丝竹和民族管弦乐中承担重要声部。",
        "parts": ["面板", "琴码", "琴弦", "滚轴板", "盖板", "共鸣箱", "琴竹"],
        "techniques": ["单竹", "双竹", "轮音", "衬音", "拨奏"],
        "heritage": ["广东音乐", "江南丝竹", "四川扬琴"],
        "gradient": "linear-gradient(135deg, #f1c27d, #9a5d1f)",
    },
    {
        "id": "dizi",
        "image": "/static/photos/dizi.jpg",
        "name": "笛子",
        "pinyin": "Dizi",
        "category": "吹管",
        "tone": "清亮、穿透，笛膜带来独特沙沙共鸣",
        "era": "新石器骨笛源流，竹笛长期发展",
        "summary": "竹笛轻巧却极具表现力，南方曲笛柔美婉转，北方梆笛高亢明亮。笛膜让它拥有鲜明的东方音色。",
        "story": "从贾湖骨笛到昆曲曲笛，再到现代协奏曲，笛子跨越了礼乐、戏曲与舞台独奏。",
        "parts": ["吹孔", "膜孔", "按音孔", "基音孔", "笛塞", "笛身"],
        "techniques": ["吐音", "打音", "历音", "花舌", "循环换气"],
        "heritage": ["昆曲伴奏", "北方梆笛", "江南丝竹"],
        "gradient": "linear-gradient(135deg, #9ec88f, #2f5b3b)",
    },
    {
        "id": "suona",
        "image": "/static/photos/suona.jpg",
        "name": "唢呐",
        "pinyin": "Suona",
        "category": "吹管",
        "tone": "高亢、热烈、穿透力极强",
        "era": "明代以来广泛民间化",
        "summary": "唢呐声音明亮强劲，常用于礼俗、戏曲和节庆，也能在现代作品中呈现极强的戏剧张力。",
        "story": "唢呐扎根民间礼俗，从婚丧嫁娶到戏曲锣鼓，记录了中国人情社会的喜怒哀乐。",
        "parts": ["哨片", "气盘", "芯子", "杆身", "音孔", "碗口"],
        "techniques": ["吐音", "滑音", "花舌", "循环换气", "模仿音"],
        "heritage": ["鲁西南鼓吹乐", "晋北鼓乐", "东北鼓吹"],
        "gradient": "linear-gradient(135deg, #ef7d57, #8f1e1b)",
    },
    {
        "id": "guqin",
        "image": "/static/photos/guqin.jpg",
        "name": "古琴",
        "pinyin": "Guqin",
        "category": "弹拨",
        "tone": "深沉、疏朗、余韵悠长",
        "era": "三千年以上文人传统",
        "summary": "古琴七弦十三徽，以散音、泛音、按音构成含蓄深远的声腔，被视为中国文人音乐精神的核心。",
        "story": "琴棋书画中的琴即古琴，讲究修身、听心与天地节律，代表曲目有《流水》《梅花三弄》《广陵散》。",
        "parts": ["琴面", "琴底", "岳山", "龙龈", "徽位", "雁足", "琴弦"],
        "techniques": ["泛音", "吟猱", "绰注", "撮", "轮指"],
        "heritage": ["虞山派", "广陵派", "梅庵派", "浙派"],
        "gradient": "linear-gradient(135deg, #c8a96a, #34251a)",
    },
    {
        "id": "zhongruan",
        "image": "/static/photos/zhongruan.jpg",
        "name": "中阮",
        "pinyin": "Zhongruan",
        "category": "弹拨",
        "tone": "温润、圆厚，兼具节奏与和声能力",
        "era": "阮咸源流，现代民族乐队定型",
        "summary": "中阮圆形共鸣箱与四弦定弦让它在独奏、重奏与民族管弦乐中兼具旋律、和声和节奏功能。",
        "story": "阮类乐器因竹林七贤阮咸善弹而得名，现代中阮常承担民族乐队中的中声部。",
        "parts": ["琴头", "品位", "圆形共鸣箱", "面板", "琴码", "覆手", "琴弦"],
        "techniques": ["弹挑", "轮指", "扫弦", "双音", "泛音"],
        "heritage": ["民族室内乐", "现代国乐团", "弹拨乐重奏"],
        "gradient": "linear-gradient(135deg, #d6b17b, #5b3325)",
    },
    {
        "id": "sanxian",
        "image": "/static/photos/sanxian.jpg",
        "name": "三弦",
        "pinyin": "Sanxian",
        "category": "弹拨",
        "tone": "干净、质朴、颗粒感强",
        "era": "元明以来广泛用于说唱与戏曲",
        "summary": "三弦琴颈无品，三根弦跨过蟒皮或木面共鸣箱，擅长滑音和说唱伴奏中的弹性节奏。",
        "story": "三弦扎根曲艺与戏曲，北方大鼓、京韵大鼓、苏州评弹等传统中都能听见它的骨架声部。",
        "parts": ["琴头", "琴杆", "弦轴", "琴鼓", "琴皮", "琴码", "三弦"],
        "techniques": ["弹挑", "滚奏", "滑音", "打弦", "扫弦"],
        "heritage": ["曲艺伴奏", "戏曲音乐", "评弹传统"],
        "gradient": "linear-gradient(135deg, #d19a57, #382218)",
    },
    {
        "id": "konghou",
        "image": "/static/photos/konghou.jpg",
        "name": "箜篌",
        "pinyin": "Konghou",
        "category": "弹拨",
        "tone": "华丽、空灵，泛音丰富",
        "era": "汉唐兴盛，现代复原发展",
        "summary": "箜篌是中国古代竖箜篌与卧箜篌传统的现代复兴形态，兼具竖琴般的华彩和东方装饰性。",
        "story": "敦煌与唐代图像中常见箜篌形象，现代箜篌通过双排弦与转调结构重新进入舞台。",
        "parts": ["琴柱", "共鸣箱", "双排弦", "调音轴", "踏板", "琴座"],
        "techniques": ["琶音", "滑奏", "泛音", "双手轮奏", "揉弦"],
        "heritage": ["唐乐复兴", "敦煌乐舞", "现代国乐创作"],
        "gradient": "linear-gradient(135deg, #ead2a2, #6b3f83)",
    },
    {
        "id": "sheng",
        "image": "/static/photos/sheng.jpg",
        "name": "笙",
        "pinyin": "Sheng",
        "category": "吹管",
        "tone": "簧片和声，明亮而立体",
        "era": "先秦礼乐已有记载",
        "summary": "笙由多根簧管组成，是中国传统乐器中少见可自然演奏和声的吹管乐器。",
        "story": "从《诗经》中的笙簧到现代键笙，笙长期连接雅乐、民间吹打和当代室内乐。",
        "parts": ["笙斗", "笙苗", "簧片", "按孔", "吹嘴", "扩音管"],
        "techniques": ["和音", "吐音", "颤音", "花舌", "循环换气"],
        "heritage": ["雅乐", "吹打乐", "现代笙协奏曲"],
        "gradient": "linear-gradient(135deg, #c7d58b, #36513a)",
    },
    {
        "id": "xiao",
        "image": "/static/photos/xiao.jpg",
        "name": "箫",
        "pinyin": "Xiao",
        "category": "吹管",
        "tone": "幽静、温润、气息感强",
        "era": "古代竖吹乐器传统",
        "summary": "箫为竖吹竹管乐器，音色沉稳内敛，常与古琴合奏，表达清雅、悠远的审美。",
        "story": "琴箫合奏是文人音乐的重要场景，箫声重在气口与余韵，适合慢板与长线条旋律。",
        "parts": ["吹口", "指孔", "出音孔", "竹管", "校音孔", "尾端"],
        "techniques": ["气震音", "滑音", "打音", "叠音", "弱奏"],
        "heritage": ["琴箫合奏", "昆曲", "江南丝竹"],
        "gradient": "linear-gradient(135deg, #9dbd8e, #243c2d)",
    },
    {
        "id": "xun",
        "image": "/static/photos/xun.jpg",
        "name": "埙",
        "pinyin": "Xun",
        "category": "吹管",
        "tone": "苍茫、古朴、近似大地回声",
        "era": "新石器时代陶制吹奏乐器",
        "summary": "埙多为陶制闭管吹奏乐器，音色浑厚幽远，是中国最古老的吹奏乐器之一。",
        "story": "埙的声音常被用于表现上古、祭祀与苍凉意境，现代作品中也常承担空间感与历史感。",
        "parts": ["吹孔", "音孔", "陶腔", "共鸣体", "底孔"],
        "techniques": ["俯吹", "滑音", "气震音", "弱奏", "装饰音"],
        "heritage": ["考古复原", "雅乐想象", "现代民族音乐"],
        "gradient": "linear-gradient(135deg, #b77b4f, #3a2318)",
    },
    {
        "id": "hulusi",
        "image": "/static/photos/hulusi.jpg",
        "name": "葫芦丝",
        "pinyin": "Hulusi",
        "category": "吹管",
        "tone": "柔美、甜润，带有少数民族风情",
        "era": "云南少数民族民间乐器",
        "summary": "葫芦丝由葫芦与竹管构成，主管演奏旋律，副管可形成持续音，音色亲切柔和。",
        "story": "葫芦丝流行于傣、阿昌等民族地区，现代教学和大众演奏让它成为入门友好的民族乐器。",
        "parts": ["葫芦", "主管", "副管", "簧片", "音孔", "尾塞"],
        "techniques": ["吐音", "滑音", "打音", "颤音", "倚音"],
        "heritage": ["傣族音乐", "云南民歌", "大众民族器乐教育"],
        "gradient": "linear-gradient(135deg, #d7a65d, #355f3a)",
    },
    {
        "id": "matouqin",
        "image": "/static/photos/matouqin.jpg",
        "name": "马头琴",
        "pinyin": "Matouqin",
        "category": "拉弦",
        "tone": "辽阔、低沉，富有草原叙事感",
        "era": "蒙古族传统拉弦乐器",
        "summary": "马头琴琴头常雕马首，两弦以弓擦弦发声，善于模仿马嘶和草原长调的悠远线条。",
        "story": "马头琴与蒙古族长调、英雄史诗和草原生活紧密相关，是北方民族音乐的重要象征。",
        "parts": ["马头琴首", "琴杆", "共鸣箱", "琴弦", "琴码", "琴弓"],
        "techniques": ["长弓", "揉弦", "泛音", "滑音", "马嘶模仿"],
        "heritage": ["蒙古族长调", "呼麦伴奏", "草原史诗"],
        "gradient": "linear-gradient(135deg, #d8b482, #463020)",
    },
    {
        "id": "bianzhong",
        "image": "/static/photos/bianzhong.jpg",
        "name": "编钟",
        "pinyin": "Bianzhong",
        "category": "打击",
        "tone": "庄严、金石感强，音高稳定",
        "era": "西周至战国礼乐高峰",
        "summary": "编钟由多枚青铜钟按音高排列，可演奏旋律与和声，是中国青铜礼乐文明的代表。",
        "story": "曾侯乙编钟展现了先秦高度发达的律学与铸造技术，至今仍震撼世界音乐史。",
        "parts": ["钟体", "钟钮", "枚", "鼓部", "钟架", "击槌"],
        "techniques": ["正鼓音", "侧鼓音", "组合敲击", "礼乐合奏"],
        "heritage": ["礼乐制度", "考古复原", "博物馆音乐展演"],
        "gradient": "linear-gradient(135deg, #b8975a, #263b38)",
    },
    {
        "id": "bo",
        "image": "/static/photos/bo.jpg",
        "name": "钹",
        "pinyin": "Bo",
        "category": "打击",
        "tone": "明亮、爆发，金属泛音丰富",
        "era": "古代金属打击乐传统",
        "summary": "钹由两片金属圆片相击发声，在戏曲锣鼓、民间吹打和节庆音乐中制造强烈节奏与气氛。",
        "story": "钹常与锣鼓组合使用，既能制造戏剧转折，也能推动舞龙舞狮、庙会和节庆现场的能量。",
        "parts": ["钹面", "钹心", "系绳", "边缘", "共鸣面"],
        "techniques": ["合击", "闷击", "擦击", "滚奏", "强弱对比"],
        "heritage": ["戏曲锣鼓", "民间吹打", "节庆音乐"],
        "gradient": "linear-gradient(135deg, #e1bf67, #5a421f)",
    },
]

HERO_STATS = [
    {"label": "可识别乐器类别", "value": "200+"},
    {"label": "真实照片图鉴", "value": str(len(INSTRUMENTS))},
    {"label": "乐器门类", "value": "5"},
    {"label": "移动端优先", "value": "100%"},
]
